#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.vk.flowable.mgt.domain
  type-aliases-super-type: java.lang.Object
  global-config:
    #刷新mapper 调试神器
    refresh: true
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
